export const routes = {
  home: '/',
  servicios: '/servicios',
  calculadora: '/calculadora',
  cotizacion: '/cotizacion',
  faq: '/faq',
  contacto: '/contacto',
  login: '/login',
  registro: '/registro',
  dashboard: '/dashboard',
  admin: '/admin',
  adminConfiguracion: '/admin/configuracion',
  adminPrecios: '/admin/precios',
  privacidad: '/privacidad',
};
