'use client';

import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, BookOpen, Clock, UploadCloud, CheckCircle2, Headphones, ShieldCheck, ArrowRight, XCircle, FileText } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { RotatingTagline } from '@/components/ui/RotatingTagline';
import { getEditorialJourneyPresentation } from '@/domain/view-models/editorialJourneyPresentation';
import type { EditorialJourney } from '@/types/domain.types';
import type { DashboardRequestState } from '@/services/dashboard-workspace.service';

interface StatusHeroProps {
  state: DashboardRequestState;
  projectTitle?: string | null;
  submittedDate?: string | null;
  progress?: number;
  statusLabel?: string;
  journey?: EditorialJourney | null;
  proposalSentAt?: string | null;
  onUploadClick: () => void;
  onViewFilesClick?: () => void;
  onToggleCarousel?: () => void;
  onOpenBriefClick?: () => void;
}

export function StatusHero({ state, projectTitle, submittedDate, progress = 0, statusLabel, journey, proposalSentAt, onUploadClick, onViewFilesClick, onToggleCarousel, onOpenBriefClick }: StatusHeroProps) {
  if (state === 'none') return <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl bg-surface-elevated/90 p-5 sm:p-8 md:p-12"><div className="relative z-10 max-w-2xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-accent/8 px-4 py-1.5 text-[11px] font-medium tracking-wide text-accent"><Sparkles className="h-3.5 w-3.5" />Centro del Autor · Studio Flamkit</div><RotatingTagline className="font-serif text-3xl sm:text-4xl lg:text-5xl" /><p className="mt-5 text-base leading-relaxed text-ink-muted/90 sm:text-lg">Envía tu manuscrito a nuestra dirección editorial. Evaluamos el tono, la estructura y la atmósfera dramatúrgica de tu obra en menos de 48 horas.</p><div className="mt-8"><Button variant="primary" onClick={onUploadClick}><UploadCloud className="h-4 w-4" />Enviar Manuscrito para Evaluación<ArrowRight className="h-3.5 w-3.5" /></Button></div><div className="mt-10 flex flex-wrap items-center gap-8 border-t border-edge/50 pt-6 text-xs text-ink-muted/80"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-accent/90" />Resguardo confidencial de propiedad intelectual</div><div className="flex items-center gap-2"><Clock className="h-4 w-4 text-accent/90" />Diagnóstico técnico en 24–48 horas</div></div></div></motion.div>;

  if (state === 'rejected') return <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl border border-rose-500/25 bg-surface-elevated/95 p-5 sm:p-8 md:p-12"><div className="relative z-10 max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-rose-500/30 bg-rose-500/10 px-4 py-1.5 text-[11px] font-medium tracking-wide text-rose-700 dark:text-rose-300"><XCircle className="h-3.5 w-3.5" />Solicitud finalizada</div><h1 className="font-serif text-2xl sm:text-4xl lg:text-5xl">{projectTitle ? `«${projectTitle}» no continuará en esta ocasión.` : 'Tu solicitud no continuará en esta ocasión.'}</h1><p className="mt-4 text-sm sm:text-base leading-relaxed text-ink-muted">{submittedDate ? `Registrado el ${submittedDate}. ` : ''}El análisis editorial ha concluido. Revisa tus notificaciones para consultar la comunicación del equipo.</p>{onViewFilesClick && <div className="mt-8"><Button variant="secondary" onClick={onViewFilesClick}><BookOpen className="h-4 w-4 text-accent" />Ver Manuscrito en Custodia</Button></div>}</div></motion.div>;

  if (state === 'proposal' || state === 'proposal_sent') {
    const published = state === 'proposal_sent' || Boolean(proposalSentAt);
    return <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl border border-amber-500/25 bg-surface-elevated/95 p-5 sm:p-8 md:p-12"><div className="relative z-10 max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-amber-500/30 bg-amber-500/10 px-3.5 py-1 text-[11px] font-semibold uppercase tracking-[0.15em] text-amber-800 dark:text-amber-300"><FileText className="h-3.5 w-3.5" />{published ? 'Propuesta disponible' : 'Propuesta en preparación'}</div><h1 className="font-serif text-3xl sm:text-4xl lg:text-5xl">{projectTitle ? `«${projectTitle}» está en la etapa de propuesta.` : 'Tu obra está en la etapa de propuesta.'}</h1><p className="mt-4 text-sm sm:text-base leading-relaxed text-ink-muted">{published ? 'La propuesta ya está disponible para tu revisión. Aún no estás en producción; primero debes aceptar la oferta.' : 'El análisis terminó y Studio FLAMKIT está preparando la oferta comercial y técnica. Todavía no estás en producción.'}</p><div className="mt-8 flex flex-wrap items-center gap-4">{published && <Button variant="primary" onClick={() => { window.location.assign('/dashboard/propuestas'); }}><FileText className="h-4 w-4" />Ver propuesta<ArrowRight className="h-3.5 w-3.5" /></Button>}{onViewFilesClick && <Button variant="secondary" onClick={onViewFilesClick}><BookOpen className="h-4 w-4 text-accent" />Ver Manuscrito en Custodia</Button>}</div></div></motion.div>;
  }

  const presentation = getEditorialJourneyPresentation(journey, state === 'pending' ? 'pending' : 'active');
  const effectiveProgress = progress;
  const effectiveLabel = journey ? presentation.label : (statusLabel || presentation.label);

  if (state === 'pending') return <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl bg-surface-elevated/95 p-5 sm:p-8 md:p-12"><div className="relative z-10 max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-amber-500/10 px-4 py-1.5 text-[11px] font-medium tracking-wide text-amber-800 dark:text-amber-300"><Clock className="h-3.5 w-3.5" />{effectiveLabel === 'Sin manuscrito' ? 'Manuscrito Recibido' : effectiveLabel}</div><h1 className="font-serif text-2xl sm:text-4xl lg:text-5xl">{projectTitle ? `«${projectTitle}» está en proceso de lectura.` : 'Tu obra está en lectura por nuestro equipo artístico.'}</h1><p className="mt-4 text-sm sm:text-base leading-relaxed text-ink-muted">{submittedDate ? `Registrado el ${submittedDate}. ` : ''}{presentation.nextActionDescription}</p><div className="mt-8 flex flex-wrap items-center gap-4">{onOpenBriefClick && <Button variant="primary" onClick={onOpenBriefClick}><Sparkles className="h-4 w-4" />Completar / Editar Brief Editorial</Button>}{onToggleCarousel && <Button variant="secondary" onClick={onToggleCarousel}><Clock className="h-4 w-4 text-accent" />Ver Ruta Editorial</Button>}{onViewFilesClick && <Button variant="secondary" onClick={onViewFilesClick}><BookOpen className="h-4 w-4 text-accent" />Ver Manuscrito en Custodia</Button>}</div></div></motion.div>;

  return <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl bg-surface-elevated/95 p-5 sm:p-8 md:p-12"><div className="relative z-10 flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div className="max-w-2xl"><div className="mb-4 flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-3.5 py-1 text-[11px] font-medium text-emerald-800 dark:text-emerald-300"><CheckCircle2 className="h-3.5 w-3.5" />{effectiveLabel || statusLabel || 'En Producción Audiocinematográfica'}</span><span className="text-xs text-ink-muted/70 tracking-wide font-mono">Obra Activa</span></div><h1 className="font-serif text-3xl sm:text-4xl lg:text-5xl">{projectTitle || 'Proyecto sin título'}</h1><p className="mt-3 text-sm leading-relaxed text-ink-muted">Monitoreo en tiempo real de grabaciones, edición musical, mezclas y aprobación de capítulos máster.</p></div><div className="flex shrink-0 flex-col items-start rounded-2xl bg-surface/80 p-6 sm:min-w-[240px]"><div className="flex items-center justify-between w-full mb-3"><span className="text-[10px] font-medium uppercase tracking-[0.22em] text-ink-muted">Avance General</span><span className="font-serif text-xl font-semibold text-accent">{effectiveProgress}%</span></div><div className="h-2 w-full rounded-full bg-edge/60 overflow-hidden"><motion.div className="h-full rounded-full bg-accent" initial={{ width: 0 }} animate={{ width: `${effectiveProgress}%` }} transition={{ duration: 1 }} /></div><div className="mt-4 flex items-center gap-2 text-xs text-ink-muted/90"><Headphones className="h-3.5 w-3.5 text-accent" />Cabina de producción activa</div></div></div></motion.div>;
}
